### ISSUE TITLE
Reproduction of "FedDF" approach

### ISSUE THREAD

**Issue by MichaelLee-ceo** [ZhangLin-PKU/FedFTG#1]
Thank you for open-sourcing your project. I notice that "FedDF" (Ensemble Distillation for Robust Model Fusion in Federated Learning) is one of your baselines in your paper, however, you provide code for only FedAvg, FedProx, FedDyn...
Do you have the implementation of FedDF?
Thanks!

**Comment by ZhangLin-PKU** [comment]
I will add FedDF method soon.

**Comment by MichaelLee-ceo** [comment]
Thanks!

**Comment by ZhangLin-PKU** [comment]
Hi @MichaelLee-ceo, I have added FedDF method. You can quickly run it using `scripts/CIFAR10_FedDF.sh`.
