### ISSUE TITLE
Request for FedGen Code about FedFTG

### ISSUE THREAD

**Issue by lloveapple** [ZhangLin-PKU/FedFTG#3]
I hope this email finds you well. I would like to express my gratitude for your captivating and outstanding work titled "Fine-Tuning Global Model via Data-Free Knowledge Distillation for Non-IID Federated Learning." The innovative approach and the extensive experiments provided significant insights into the challenges of federated learning, and I found your paper to be highly inspiring.

I am currently working on a research project where I urgently need the implementation code for FedGen as one of the comparison methods. I would greatly appreciate it if you could send me the FedGen code, as it is crucial for the continuation of my research.

Thank you very much for your time and assistance. I look forward to your response.

Best regards,
Xiao Yang
School of Information Science and Engineering
Lanzhou University
Lanzhou, 730000, Gansu, China
Email: 220220942491@lzu.edu.cn

**Comment by ZhangLin-PKU** [comment]
@lloveapple Sorry I didn't notice this issue. 

The code of FedGen is published by its author. Here is the link: https://github.com/zhuangdizhu/FedGen/tree/main.

Thanks.
